#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 2e518a27-2dea-483d-8147-e5e1ff4e737f
# Source File: ..\OneDrive - Florida State University\Documents\SAPIEN\PowerShell Studio\Files\tooltesting.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
mgcAAB+LCAAAAAAABABlVUcPo4gOvkfKfxjtFWmpoUgzIxEg9N650ULvLfDrX3beZaX1ybJsH+yv
/LTydNjz+WTjNf7xTZZq6H/9hf4N//X7fvvx46c+V0XVx+2ranMt7vLf6zC0a76sVV/8PS7vn+B/
Ov7MvYa5+83m+AA764RWJE0zOsvQ/48nzWZduxrYVbgfigqQjTSppGMeq6RIcsFFXleOji6qi1rb
rRxETV+fTYsgYA/dbymqjI42x2TwkpWTbiy5X1PgAi8yR1NQ8MAow9LMAcmD0jayAGPjdToVlgyI
6zZUHy0fQMffoIXYcHu/LeAHdQGNgjMb4D7JQ1NO6Grn0YHVROL4VBXEqKmszllZVyhFlFRg8DRk
aR+FA9pgpE+SgNgqJI5e/v12IY9hcFT2/GiDg1ADuprGp7hkzQyh+tloQ5N0Ul3jh16li1BGnlLK
YT2fvcimAKvaY/OgIffhQCSi3G8k7Fl+5pZCpPHgJ1zsfFHpEeDItAZpy8PbFXUHej/tlT791GK5
Kq47o788DygejB5xetVb2FQFLebeb9socbHHhRWoedMlXgHwRIcHoA2Ks3CfUtrIT4dAAQgUAO5L
NjGSOBYbagu+98owVsTzLJ11HOBsiu+2wFkXAmRVBt624xwipMT1HBge6rs28eeGIJml5sjqWqqW
rUM3tJJe4wTSRd3hnKsgpTnIqF5LCyZh3m8PsMcwysecTQ7LfgmOBVVZWqkWbcB5fsBb7qyivAzx
agg7XYkeqoKTFVTR15SYBJgVsuUJRx+GPYHdb8hWgEvoFN1ebxbWOLUutaaMZQQC0zQ5c1S6OgIn
xxQRIgUDRvsVd1stze9Ljy8ZHMMNgPY45gNlGu43I09XCKNfNK4t1zrsBVLbznPzmWWfppnnYwuQ
a0SUbXJaOcgMvV7EdgjrjOrAoylf0dAbcxXgwwb4orev6Nmq3dlLHPqxiEfOzXKqc0+psDv4CK9e
KnYzjrXZo7UrJcKdXjBZMPO3D8Ran4p5WYf2nPUiHwX323OkOTGDpzRYlmIqF77tPqLcKAzSCD6e
c9w8ylYRvffde2GE6RH5Ocj/0PL40pLe408mOVxpzY8Vet1ve5Cl3PbJzoqB1YGtA7ZEEFor1QuU
a8yQly4UDuRcyvAlafOirVmzkiUanbIB6gPyxlkkKoTne3pK+hdvBTazAX56D1iY+mecfXFNwAjV
5oZrJ5AS5uGb94ynNsU21CAgizEDGsOCLICsZIsQTtUWqV3Ah2y2+63VkYxacPxydl98RRKqxcgq
QAjg8Bhdlkpo76oO1C5kMDTnvweA5lXsLHg1VkIKN8sRSugpioHpFKn7DUUyl36UhXgUcFmzrswA
rzePy0LXyUE8XsSOYWIaxHJsitlK2JUoJ8Tki0O5YIXszRCTKnLsEwVnCPfbS/YTXhSMHMPGfNkW
Drbc89W8WlNLz+6TP5n9zXxI86J2ayWWZPXWL+2piu/derdaDj0VkCqfYJ0dzv1WMA7PGDrj1gcv
trAVbXHDma/3i9xm0imp49RtIeOIBVFinmmVRb6Iakr4pGodCNKcBuyayanh7V1LX55WOB/pETPB
GvheyyIE+Y1iBhrpaR+EiQwaXcscA51TJxIanRRoDzXI0IaYGNTNQdWNMnSVCbrS9f1+M7eJxZXR
qp8yT5ZnO3221RUSY37Mk/FEx4gP/LdlGUfCYATW2+nH7UZfWT3xe1XjYuhcdwCOgd03E321d+eu
FLP2waL4WO2UtTNbPDNtfjYi1H0N6N6kcmLjiZjb87PCkaWZkOTi+kvyHzv9RAZFTyNg/3DS96eb
ZkNcwIcaDq2mm+9NtPkI5MyQEnsNZRyb3w4Bhmc9GzdMUJpXyypBAD7A1N9yfxSqNSWeJp3QZPRV
8u2ViB65M5m3rMzE2rDFlvmOsIHKapQ+URNZStAS9rOeTwnrfwzbSsNMEReiWdolmin/7YJHb0vu
rn3x9o8D0r9+/QT/GOMfi6SXJe+StsqXH+C38hP8txf//h+TNEtJmgcAAA==#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2020 v5.7.174
     Generated on:       10/15/2021 1:30 PM
     Generated by:       adm-tyler
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2020
#>

#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------


function Show-tooltesting_psf {


	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()

	$form1 = New-Object 'System.Windows.Forms.Form'
	$progressbar1 = New-Object 'System.Windows.Forms.ProgressBar'
	$buttonClear = New-Object 'System.Windows.Forms.Button'
	$groupbox1 = New-Object 'System.Windows.Forms.GroupBox'
	$groupbox2 = New-Object 'System.Windows.Forms.GroupBox'
	$richtextbox7 = New-Object 'System.Windows.Forms.RichTextBox'
	$richtextbox6 = New-Object 'System.Windows.Forms.RichTextBox'
	$labelCalendarPermissions = New-Object 'System.Windows.Forms.Label'
	$labelInboxPermissions = New-Object 'System.Windows.Forms.Label'
	$richtextbox5 = New-Object 'System.Windows.Forms.RichTextBox'
	$labelMailboxStatistics = New-Object 'System.Windows.Forms.Label'
	$richtextbox4 = New-Object 'System.Windows.Forms.RichTextBox'
	$labelMailboxInformation = New-Object 'System.Windows.Forms.Label'
	$labelFSUID = New-Object 'System.Windows.Forms.Label'
	$labelProxyAddresses = New-Object 'System.Windows.Forms.Label'
	$labelGroupMembership = New-Object 'System.Windows.Forms.Label'
	$labelADObjectInformation = New-Object 'System.Windows.Forms.Label'
	$richtextbox3 = New-Object 'System.Windows.Forms.RichTextBox'
	$richtextbox2 = New-Object 'System.Windows.Forms.RichTextBox'
	$textbox1 = New-Object 'System.Windows.Forms.TextBox'
	$buttonSearch = New-Object 'System.Windows.Forms.Button'
	$richtextbox1 = New-Object 'System.Windows.Forms.RichTextBox'
	$contextmenustrip1 = New-Object 'System.Windows.Forms.ContextMenuStrip'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$form1_Load={
		#TODO: Initialize Form Controls here
		
	}
	
	
	$buttonSearch_MouseClick = [System.Windows.Forms.MouseEventHandler]{
		
	
	#Event Argument: $_ = [System.Windows.Forms.MouseEventArgs]
		#TODO: Place custom script here
		$progressbar1.Maximum = 8
		$progressbar1.Minimum = 0
		$progressbar1.Value=1
		
		$AD = Get-ADUser $textbox1.Text -Properties * 
		$richtextbox1.Text = $AD <# Do Select Object for what properties you want to show for AD object#>| Out-String

		$progressbar1.Value = 2
		#Grab Group Membership
		$membersof = @()
		foreach ($object in $ad.MemberOf) { $membersof += (get-adgroup $object).name }
		$richtextbox2.Text = $membersof | Out-String
		
		#grab ProxyAdrresses
		$proxyaddresses = $ad.proxyAddresses
		$richtextbox3.Text = $proxyaddresses | Out-String
		$progressbar1.Value = 3
		
		#mailbox Information
		$Mailbox = get-mailbox $textbox1.Text
		$richtextbox4.Text = $Mailbox | Select Forwardingaddress, SMTPForwardingAddress, Delivertomailboxandforward, HiddenFromAddressListsEnabled | Out-String
		$progressbar1.Value = 4
		$Statistics = get-mailboxstatistics $textbox1.Text
		$richtextbox5.Text = $Statistics.TotalItemSize
		$progressbar1.Value = 5
		
		#mailbox Perms
		$inbox = $Mailbox.UserPrincipalName + ":\Inbox"
		$calendar = $Mailbox.UserPrincipalName + ":\Calendar"
		$progressbar1.Value = 6
		
		$inboxperms = Get-MailboxFolderPermission $inbox
		$calendarperms = Get-MailboxFolderPermission $calendar
		
		$richtextbox6.Text = $inboxperms | Select User, Accessrights | Out-String
		$richtextbox7.Text = $calendarperms | Select User, Accessrights | Out-String
		$progressbar1.Value = 7
		$progressbar1.Value = 8
	}
	
	$buttonClear_Click={
		#TODO: Place custom script here
		$textbox1.Text = $null
		$richtextbox1.Text = $null
		$richtextbox2.Text = $null
		$richtextbox3.Text = $null
		$richtextbox4.Text = $null
		$richtextbox5.Text = $null
		$richtextbox6.Text = $null
		$richtextbox7.Text = $null
		$progressbar1.Value = 0
	}
	
	
	$buttonStartProcess_Click={
		#Init CancelLoop
		$script:CancelLoop = $false
		$buttonCancelProcess.Enabled = $true
		#Disable the button so we don't trigger it again
		$this.Enabled = $false
		#Reset the Progress Bar
		$progressbar1.Value = 0
		
		for($i = 0; $i -lt $progressbar1.Maximum; $i++)
		{
			#----------------------------------------
			#Place custom script here
			sleep -Milliseconds 200
			
			#----------------------------------------
			#process the pending message
			[System.Windows.Forms.Application]::DoEvents()
			
			if($script:CancelLoop -eq $true)
			{
				#Clear the progress bar
				$progressbar1.Value = 0
				#Exit the loop
				break;
			}
			#Step the progress bar
			$progressbar1.PerformStep() 
		}
		
		#Enable the button so we can click it again
		$this.Enabled = $true
		$buttonCancelProcess.Enabled = $false
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$form1.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonClear.remove_Click($buttonClear_Click)
			$buttonSearch.remove_MouseClick($buttonSearch_MouseClick)
			$form1.remove_Load($form1_Load)
			$form1.remove_Load($Form_StateCorrection_Load)
			$form1.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$form1.SuspendLayout()
	$groupbox1.SuspendLayout()
	$groupbox2.SuspendLayout()
	#
	# form1
	#
	$form1.Controls.Add($progressbar1)
	$form1.Controls.Add($buttonClear)
	$form1.Controls.Add($groupbox1)
	$form1.Controls.Add($labelFSUID)
	$form1.Controls.Add($labelProxyAddresses)
	$form1.Controls.Add($labelGroupMembership)
	$form1.Controls.Add($labelADObjectInformation)
	$form1.Controls.Add($richtextbox3)
	$form1.Controls.Add($richtextbox2)
	$form1.Controls.Add($textbox1)
	$form1.Controls.Add($buttonSearch)
	$form1.Controls.Add($richtextbox1)
	$form1.AutoScaleDimensions = '6, 13'
	$form1.AutoScaleMode = 'Font'
	$form1.ClientSize = '849, 561'
	$form1.ContextMenuStrip = $contextmenustrip1
	$form1.Name = 'form1'
	$form1.Text = 'Form'
	$form1.add_Load($form1_Load)
	#
	# progressbar1
	#
	$progressbar1.Location = '293, 39'
	$progressbar1.Name = 'progressbar1'
	$progressbar1.Size = '118, 23'
	$progressbar1.TabIndex = 13
	#
	# buttonClear
	#
	$buttonClear.Location = '223, 39'
	$buttonClear.Name = 'buttonClear'
	$buttonClear.Size = '64, 23'
	$buttonClear.TabIndex = 12
	$buttonClear.Text = 'Clear'
	$buttonClear.UseCompatibleTextRendering = $True
	$buttonClear.UseVisualStyleBackColor = $True
	$buttonClear.add_Click($buttonClear_Click)
	#
	# groupbox1
	#
	$groupbox1.Controls.Add($groupbox2)
	$groupbox1.Controls.Add($richtextbox5)
	$groupbox1.Controls.Add($labelMailboxStatistics)
	$groupbox1.Controls.Add($richtextbox4)
	$groupbox1.Controls.Add($labelMailboxInformation)
	$groupbox1.Location = '432, 12'
	$groupbox1.Name = 'groupbox1'
	$groupbox1.Size = '399, 447'
	$groupbox1.TabIndex = 11
	$groupbox1.TabStop = $False
	$groupbox1.Text = 'Office 365 Information'
	$groupbox1.UseCompatibleTextRendering = $True
	#
	# groupbox2
	#
	$groupbox2.Controls.Add($richtextbox7)
	$groupbox2.Controls.Add($richtextbox6)
	$groupbox2.Controls.Add($labelCalendarPermissions)
	$groupbox2.Controls.Add($labelInboxPermissions)
	$groupbox2.Location = '6, 227'
	$groupbox2.Name = 'groupbox2'
	$groupbox2.Size = '385, 213'
	$groupbox2.TabIndex = 15
	$groupbox2.TabStop = $False
	$groupbox2.Text = 'Office 365 Information'
	$groupbox2.UseCompatibleTextRendering = $True
	#
	# richtextbox7
	#
	$richtextbox7.Location = '6, 140'
	$richtextbox7.Name = 'richtextbox7'
	$richtextbox7.Size = '373, 67'
	$richtextbox7.TabIndex = 17
	$richtextbox7.Text = ''
	#
	# richtextbox6
	#
	$richtextbox6.Location = '6, 47'
	$richtextbox6.Name = 'richtextbox6'
	$richtextbox6.Size = '373, 70'
	$richtextbox6.TabIndex = 16
	$richtextbox6.Text = ''
	#
	# labelCalendarPermissions
	#
	$labelCalendarPermissions.AutoSize = $True
	$labelCalendarPermissions.Location = '6, 120'
	$labelCalendarPermissions.Name = 'labelCalendarPermissions'
	$labelCalendarPermissions.RightToLeft = 'No'
	$labelCalendarPermissions.Size = '115, 17'
	$labelCalendarPermissions.TabIndex = 13
	$labelCalendarPermissions.Text = 'Calendar Permissions'
	$labelCalendarPermissions.UseCompatibleTextRendering = $True
	#
	# labelInboxPermissions
	#
	$labelInboxPermissions.AutoSize = $True
	$labelInboxPermissions.Location = '6, 27'
	$labelInboxPermissions.Name = 'labelInboxPermissions'
	$labelInboxPermissions.RightToLeft = 'No'
	$labelInboxPermissions.Size = '97, 17'
	$labelInboxPermissions.TabIndex = 12
	$labelInboxPermissions.Text = 'Inbox Permissions'
	$labelInboxPermissions.UseCompatibleTextRendering = $True
	#
	# richtextbox5
	#
	$richtextbox5.Location = '6, 191'
	$richtextbox5.Name = 'richtextbox5'
	$richtextbox5.Size = '385, 30'
	$richtextbox5.TabIndex = 14
	$richtextbox5.Text = ''
	#
	# labelMailboxStatistics
	#
	$labelMailboxStatistics.AutoSize = $True
	$labelMailboxStatistics.Location = '6, 171'
	$labelMailboxStatistics.Name = 'labelMailboxStatistics'
	$labelMailboxStatistics.RightToLeft = 'No'
	$labelMailboxStatistics.Size = '92, 17'
	$labelMailboxStatistics.TabIndex = 13
	$labelMailboxStatistics.Text = 'Mailbox Statistics'
	$labelMailboxStatistics.UseCompatibleTextRendering = $True
	#
	# richtextbox4
	#
	$richtextbox4.Location = '6, 47'
	$richtextbox4.Name = 'richtextbox4'
	$richtextbox4.Size = '385, 121'
	$richtextbox4.TabIndex = 12
	$richtextbox4.Text = ''
	#
	# labelMailboxInformation
	#
	$labelMailboxInformation.AutoSize = $True
	$labelMailboxInformation.Location = '6, 27'
	$labelMailboxInformation.Name = 'labelMailboxInformation'
	$labelMailboxInformation.RightToLeft = 'No'
	$labelMailboxInformation.Size = '103, 17'
	$labelMailboxInformation.TabIndex = 12
	$labelMailboxInformation.Text = 'Mailbox Information'
	$labelMailboxInformation.UseCompatibleTextRendering = $True
	#
	# labelFSUID
	#
	$labelFSUID.AutoSize = $True
	$labelFSUID.Location = '12, 22'
	$labelFSUID.Name = 'labelFSUID'
	$labelFSUID.Size = '38, 17'
	$labelFSUID.TabIndex = 9
	$labelFSUID.Text = 'FSUID'
	$labelFSUID.UseCompatibleTextRendering = $True
	#
	# labelProxyAddresses
	#
	$labelProxyAddresses.AutoSize = $True
	$labelProxyAddresses.Location = '12, 397'
	$labelProxyAddresses.Name = 'labelProxyAddresses'
	$labelProxyAddresses.Size = '90, 17'
	$labelProxyAddresses.TabIndex = 8
	$labelProxyAddresses.Text = 'Proxy Addresses'
	$labelProxyAddresses.UseCompatibleTextRendering = $True
	#
	# labelGroupMembership
	#
	$labelGroupMembership.AutoSize = $True
	$labelGroupMembership.Location = '12, 246'
	$labelGroupMembership.Name = 'labelGroupMembership'
	$labelGroupMembership.Size = '101, 17'
	$labelGroupMembership.TabIndex = 7
	$labelGroupMembership.Text = 'Group Membership'
	$labelGroupMembership.UseCompatibleTextRendering = $True
	#
	# labelADObjectInformation
	#
	$labelADObjectInformation.AutoSize = $True
	$labelADObjectInformation.Location = '12, 75'
	$labelADObjectInformation.Name = 'labelADObjectInformation'
	$labelADObjectInformation.Size = '115, 17'
	$labelADObjectInformation.TabIndex = 6
	$labelADObjectInformation.Text = 'AD Object Information'
	$labelADObjectInformation.UseCompatibleTextRendering = $True
	#
	# richtextbox3
	#
	$richtextbox3.Location = '12, 415'
	$richtextbox3.Name = 'richtextbox3'
	$richtextbox3.Size = '385, 129'
	$richtextbox3.TabIndex = 5
	$richtextbox3.Text = ''
	$richtextbox3.WordWrap = $False
	#
	# richtextbox2
	#
	$richtextbox2.Location = '12, 265'
	$richtextbox2.Name = 'richtextbox2'
	$richtextbox2.Size = '385, 129'
	$richtextbox2.TabIndex = 4
	$richtextbox2.Text = ''
	#
	# textbox1
	#
	$textbox1.Location = '12, 42'
	$textbox1.Name = 'textbox1'
	$textbox1.Size = '140, 20'
	$textbox1.TabIndex = 3
	#
	# buttonSearch
	#
	$buttonSearch.Location = '161, 39'
	$buttonSearch.Name = 'buttonSearch'
	$buttonSearch.Size = '59, 23'
	$buttonSearch.TabIndex = 2
	$buttonSearch.Text = 'Search'
	$buttonSearch.UseCompatibleTextRendering = $True
	$buttonSearch.UseVisualStyleBackColor = $True
	$buttonSearch.add_MouseClick($buttonSearch_MouseClick)
	#
	# richtextbox1
	#
	$richtextbox1.Location = '12, 93'
	$richtextbox1.Name = 'richtextbox1'
	$richtextbox1.Size = '385, 150'
	$richtextbox1.TabIndex = 1
	$richtextbox1.Text = ''
	#
	# contextmenustrip1
	#
	$contextmenustrip1.Name = 'contextmenustrip1'
	$contextmenustrip1.Size = '61, 4'
	$groupbox2.ResumeLayout()
	$groupbox1.ResumeLayout()
	$form1.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $form1.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$form1.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$form1.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $form1.ShowDialog()

} #End Function


if (!(get-installedmodule exchangeonlinemanagement)) {cls
"Please install ExchangeOnlime Powershell module and run again"
pause
exit}

Connect-ExchangeOnline


#Call the form
Show-tooltesting_psf | Out-Null

Get-PSSession|Remove-PSSession
